### DISCUSSION TITLE
How can I nest entire event inside a single json field while remapping in vrl?

### DISCUSSION THREAD

**Discussion by sainad2222** [vectordotdev/vrl#1212] [Q&A] [answered]
Before:

```json
{
"field1": "val1",
"field2": "val2"
}
```

After:

```json
{
  "event": {
  "field1": "val1",
  "field2": "val2"
  },
 "event_type": "type1"
}
```

I tried this but doesn't seem to work as expected
```yaml
transforms:
  restructure_event:
    type: "remap"
    inputs:
      - "input1"
    source: |
      .event = .
      .event_type = "type1"
```

Edit:
After trying this

```
.event = merge({}, .)
.event_type = "type1"
```

I am able to nest but need a way to delete all fields except "event" and "event_type"
TIA
