### DISCUSSION TITLE
Potential false positive warning for an unused variable in VRL

### DISCUSSION THREAD

**Discussion by maxdialpad** [vectordotdev/vrl#1245] [Q&A] [answered]
Hello,

Is this a false positive warning or am I doing something incorrectly here?
```
[transforms.utils_log_pre_processor]
  type = "remap"
  inputs = ["..."]
  source = '''
    vector_ingest_time = now()
    match, err = parse_json(.message)
    if err != null {
      log("Utils Pre-Processor: Failed to jsonify message with error " + err, level: "error", rate_limit_secs:1)
      abort
    } else {
      . = match
    }
    ...
  '''
```

I'm getting a warning:
```
WARN transform{component_kind="transform" component_id=utils_log_pre_processor component_type=remap}: vector::transforms::remap: VRL compilation warning. warnings=
warning[E900]: unused variable `err`
  ┌─ :2:12
  │
2 │     match, err = parse_json(.message)
  │            ^^^ help: use the result of this expression or remove it
  │
  = this expression has no side-effects
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/example
```

Thanks very much!

**Comment by pront** [comment, marked as answer]
Hi @maxdialpad, I cannot reproduce this.

Config:
```
sources:
  demo_logs_1:
    type: demo_logs
    format: json


transforms:
  t0:
    type: remap
    inputs:
    - demo*
    source: |
        match, err = parse_json(.message)
        if err != null {
          log("Utils Pre-Processor: Failed to jsonify message with error " + err, level: "error", rate_limit_secs:1)
          abort
        } else {
          . = match
        }

sinks:
  console:
    type: console
    inputs: ["t0"]
    encoding:
      codec: json
      json:
        pretty: true
```

Console:
```
2025-01-31T16:17:09.372025Z  INFO vector::app: Log level is enabled. level="info,vector::sources::file=debug"
2025-01-31T16:17:09.376480Z  INFO vector::app: Loading configs. paths=["/Users/pavlos.rontidis/CLionProjects/vector/pront/configs/maybe_false_warning.yaml"]
2025-01-31T16:17:09.409182Z  INFO vector::topology::running: Running healthchecks.
2025-01-31T16:17:09.410813Z  INFO vector::topology::builder: Healthcheck passed.
2025-01-31T16:17:09.412229Z  INFO vector: Vector has started. debug="true" version="0.45.0" arch="aarch64" revision=""
...
```
