### ISSUE TITLE
object() is only sometimes fallible

### ISSUE THREAD

**Issue by byronwolfman** [vectordotdev/vrl#1041]
Related to another issue, I'm running into a funny problem where the `object()` function is only sometimes fallible.

In an earlier transform, `.` has been turned into an object. Now in a new transform, we run into the following problems:

Fails `vector validate` because `.` is considered of type `any`:
```
redact(., filters: [...])
```

Ok, no problem. We'll ensure it's an object first! The following passes `vector validate` but now fails when tests are executed because `object!()` is considered infallible:

```
original = object!(.)
redact(original, filters: [...])
```

That's strange, because the docs mark `object()` as a fallible function. Ok, well, we could try to handle the error, but this doesn't work either because errors aren't returned for infallible functions:

```
original, err = object(.)
if err != null {
  abort
}
```

The reason seems to be that `object()` is considered _sometimes_ fallible:

```rust
impl FunctionExpression for ObjectFn {
    fn resolve(&self, ctx: &mut Context) -> Resolved {
        object(self.value.resolve(ctx)?)
    }

    fn type_def(&self, state: &state::TypeState) -> TypeDef {
        self.value
            .type_def(state)
            .fallible_unless(Kind::object(Collection::any()))
            .restrict_object()
    }
}
```

Given that I'm not sure how to actually use the function. It is only possible to get a passing `vector validate` and `vector test` if you pass a non-object, e.g. `object("definite-not-an-object")` so that it can be fallible for test+validate. If an object is passed in, it's still fallible for validate, but becomes infallible for test.

**Comment by pront** [comment]
Does the following pass?

```
if is_object(.) {
    original = .
} else {
    original = object(.)
}
```

**Comment by byronwolfman** [comment]
Thanks for the suggestion but unfortunately it does not! Even when `is_object(.)` evaluates to true, `.` remains of type `any`.

If `is_object(.)` evaluates to false, then attempting to cast via `object(.)` will always fail per the description:

> Returns **value** if it is an object, otherwise returns an error. This enables the type checker to guarantee that the returned value is an object and can be used in any function that expects an object.

**Comment by pront** [comment]
Hmm, I would expect you can use the `is_object` to optionally convert the type. 
I wanted to get a minimal config to repro this, how about the following:

Config
```
sources:
  demo_logs:
    type: demo_logs

transforms:
  redact_transform:
    type: remap
    inputs:
      - demo_logs
    source: |
      .original = object!(.)
      .redacted = redact(.original, filters: [{field: "password", replacement: "[REDACTED]"}])

sinks:
  console:
    type: console
    inputs:
      - redact_transform
    encoding:
      codec: json 

```

Unit test
```
transforms:
  redact_transform:
    input: foo
    type: remap
    source: |
      . = redact(., filters: [{field: "password", replacement: "[REDACTED]"}])
tests:
  - name: redact password from logs
    inputs:
      - insert_at: redact_transform
        type: log
        log_fields:
          user: "Alice"
          password: "my-secret-password"
          message: "User logged in"
    outputs:
      - extract_from: console
        conditions:
          - .user == "Alice"
          - .message == "User logged in"
          - .password == "[REDACTED]"
```

**Comment by byronwolfman** [comment]
Thanks @pront . Yes, tests for this will pass. What I mentioned in the initial issue report is that `vector validate` will not:

```
$ vector validate vector.yaml
√ Loaded ["vector.yaml"]

Component errors
----------------
x Transform "redact_transform":
error[E620]: can't abort infallible function
  ┌─ :1:13
  │
1 │ .original = object!(.)
  │             ^^^^^^- remove this abort-instruction
  │             │
  │             this function can't fail
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples

error[E203]: syntax error
  ┌─ :2:47
  │
2 │ .redacted = redact(.original, filters: [{field: "password", replacement: "[REDACTED]"}])
  │                                               ^
  │                                               │
  │                                               unexpected syntax token: "Colon"
  │                                               expected one of: "\n", "!=", "&&", "*", "+", ",", "-", "/", ";", "<", "<=", "=", "==", ">", ">=", "??", "|", "|", "|=", "||", "}"
  │
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

**Comment by byronwolfman** [comment]
I appreciate the help. The challenge here is to write something that will pass both `vector test` **and** `vector validate`. It is possible to always pass one or the other, but never both. I am fairly certain then that this is a bug.

**Comment by byronwolfman** [comment]
Ok, I think I've found a partial cause. I was putting together a small vector config to reproduce the problem, but wasn't able to reproduce the failure. I was able to craft `original = object(.)` which passed `vector test` and `vector validate`. Weird! So what's different about this tiny config versus the one that's giving me grief?

Log namespacing. When I enable it in the proof-of-concept, I can reproduce the issue.

The following will pass `vector test` but fail `vector validate`:

```
data_dir: /tmp
schema:
  log_namespace: true

sources:
  demo:
    type: demo_logs
    format: json

transforms:
  some_transform:
    type: remap
    inputs:
      - demo
    source: |
      original = object(.)

      # This doesn't really do anything
      # But it suppresses warnings for unused vars
      if original != null {
        . = original
      }

sinks:
  console:
    type: console
    inputs:
      - some_transform
    encoding:
      codec: json 

tests:
  - name: test some_transform
    inputs:
      - insert_at: some_transform
        type: vrl
        source: |
          .message = "some message"
    outputs:
      - extract_from: some_transform
        conditions:
          - .message == "some message"
```

By swapping making the following change:

```diff
-      original = object(.)
+      original = object!(.)
```

The config will then pass `vector validate` but fail `vector test`.

**Comment by pront** [comment]
I can repro on my end. 

This Vector unit test passes:
```
transforms:
  redact_transform:
    inputs: [foo]
    type: remap
    source: |
      original = object(.)
      . =  redact(original, filters: [r'\d+'])

tests:
  - name: redact ssn from logs
    inputs:
      - insert_at: redact_transform
        type: log
        log_fields:
          user: "Alice"
          ssn: "1234"
          message: "User logged in"
    outputs:
      - extract_from: redact_transform
        conditions:
          - .user == "Alice"
          - .message == "User logged in"
          - .ssn == "[REDACTED]"
```

The following passes validation:

```
data_dir: /Users/pavlos.rontidis/CLionProjects/vector/pront_tests/data_dir
schema:
  log_namespace: true

sources:
  demo_logs:
    type: demo_logs
    format: json

transforms:
  redact_transform:
    type: remap
    inputs:
      - demo_logs
    source: |
      original = object(.)
      . =  redact(original, filters: [r'\d+'])
sinks:
  console:
    type: console
    inputs:
      - redact_transform
    encoding:
      codec: json 
```

However when I add 
```
schema:
  log_namespace: true
```

I see:
```
√ Loaded ["/Users/pavlos.rontidis/CLionProjects/vector/pront_tests/vector/configs/redact.yaml"]

Component errors
----------------
x Transform "redact_transform": 
error[E103]: unhandled fallible assignment
  ┌─ :1:12
  │
1 │ original = object(.)
  │ ---------- ^^^^^^^^^ this expression is fallible because at least one argument's type cannot be verified to be valid
  │ │
  │ or change this to an infallible assignment:
  │ original, err = object(.)
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see functions characteristics documentation at https://vrl.dev/expressions/#function-call-characteristics
  = learn more about error code 103 at https://errors.vrl.dev/103
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples

error[E701]: call to undefined variable
  ┌─ :2:13
  │
2 │ . =  redact(original, filters: [r'\d+'])
  │             ^^^^^^^^
  │             │
  │             undefined variable
  │             did you mean "null"?
  │
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples



Process finished with exit code 78
```
